fix

diff --git a/.github/workflows/quality_validations.yml b/.github/workflows/quality_validations.yml
--- a/.github/workflows/quality_validations.yml
+++ b/.github/workflows/quality_validations.yml
@@ -1,7 +1,14 @@
 name: Validação de Qualidade
-run-name: ${{ github.actor }}
+run-name: Commit ${{ github.event.head_commit.message }} enviado por @${{ github.actor }}
 
 on:
+  push:
+    branches:
+      - main
+      - Staging
+      - UAT
+      - SIT
+      
   pull_request:
     types: [opened, edited, synchronize]
     branches:
@@ -45,24 +52,33 @@ jobs:
       - name: Rodar Scanner para Salesforce Apex
         id: apex_status
         run: |
-          sfdx scanner:run -f junit -s 3 --normalize-severity -t "force-app" -e "pmd" -c "Design,Best Practices,Code Style,Performance,Security" --outfile ./reports/scan-apex.xml
-        continue-on-error: true
+          sfdx scanner:run -f sarif -s 3 --normalize-severity -t "force-app" -e "pmd" -c "Design,Best Practices,Code Style,Performance,Security" --outfile ./reports/scan-apex.sarif
 
-      - uses: actions/upload-artifact@v3
-        with:
-          name: cli-scan-report
-          path: reports/scan-apex.xml
 
-      - name: Publicar resultado dos testes sumarizado
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure()
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v1
         with:
-          report_paths: 'reports/scan-apex.xml' 
+          sarif_file: reports/scan-apex.sarif
+
+
+#      - uses: actions/upload-artifact@v3
+#        if: success() || failure()
+#        with:
+#          name: cli-scan-report
+#          path: reports/scan-apex.xml
+
+#      - name: Publicar resultado dos testes sumarizado
+#        uses: mikepenz/action-junit-report@v4
+#        if: success() || failure()
+#        with:
+#          report_paths: 'reports/scan-apex.xml' 
+#          check_name: "Qualidade de código Apex"
           
-      - name: Detalhes dos testes
-        uses: test-summary/action@v2
-        with:
-           paths: reports/scan-apex.xml
+#      - name: Detalhes dos testes
+#        uses: test-summary/action@v2
+#        if: success() || failure()
+#        with:
+#           paths: reports/scan-apex.xml
   
   quality-LWC:  
     name: Qualidade LWC
@@ -98,9 +114,9 @@ jobs:
         id: lwc_status
         run: |
             sfdx scanner:run -f junit -s 3 --normalize-severity -t "force-app" -e "eslint" --outfile ./reports/scan-lwc.xml
-        continue-on-error: true
 
       - uses: actions/upload-artifact@v3
+        if: success() || failure()
         with:
           name: cli-scan-report
           path: reports/scan-lwc.xml
@@ -110,8 +126,10 @@ jobs:
         if: success() || failure()
         with:
           report_paths: 'reports/scan-lwc.xml' 
+          check_name: "Qualidade de código LWC"
             
       - name: Detalhes dos testes
+        if: success() || failure()
         uses: test-summary/action@v2
         with:
           paths: reports/scan-lwc.xml   
@@ -120,7 +138,15 @@ jobs:
     name: Notificações e alertas
     runs-on: ubuntu-latest
     needs: [quality-Apex, quality-LWC]
+    if: always()
     steps:
+
+
+    - name: getPrUrl
+      id: pr-url
+      uses: ammaratef45/pr-url-action@v1
+    - name: display
+      run: echo ${{ steps.pr-url.outputs.url }} 
       
     - uses: ravsamhq/notify-slack-action@v2
       if: ${{ needs.quality-Apex.outputs.output1 == 'failure' && needs.quality-LWC.outputs.output1 == 'failure'}}
@@ -128,11 +154,11 @@ jobs:
           status: ${{ job.status }}
           token: ${{ github.token }}
           notification_title: 'Vulnerabilidades encontradas no ${{ github.head_ref }}'
-          message_format: ':large_orange_diamond: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} Necessária ação do time de segurança, acesse para rejeitar/aprovar a PR'
-          footer: "link do repositório <{repo_url}|{repo}> | {workflow_url}"
+          message_format: ':large_orange_diamond: ${{ steps.pr-url.outputs.url }},  Necessária ação do time de segurança, acesse para rejeitar/aprovar a PR'
+          footer: 'link do repositório <{repo_url}|{repo}> | {workflow_url}'
       env:
           SLACK_WEBHOOK_URL: ${{ secrets.ACTION_SLACK }}
-              
+  
     - uses: ravsamhq/notify-slack-action@v2
       if: always()
       with:
@@ -144,20 +170,24 @@ jobs:
       env:
           SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_TEAM_SLACK }}
 
-  pr-actions:
-    name: Ações Pull Request
-    runs-on: ubuntu-latest
-    needs: [comunicacoes]
-    permissions:
-      contents: write
-    steps:
-      
-      - uses: github/lock@v2.1.1
-        id: lock
-        if: ${{ needs.quality-Apex.outputs.output1 == 'failure' && needs.quality-LWC.outputs.output1 == 'failure'}}
-        with:
-          mode: "lock"
-          reason: "Encontrados erros na execução de qualidade de código, necessária ações do time de securança"
-          environment: ${GITHUB_REF}
-
-          
+    - name: Send mail
+      uses: dawidd6/action-send-mail@v3
+      with:
+        connection_url: ${{secrets.MAIL_CONNECTION}}
+        server_address: smtp.live.com
+        server_port: 465
+        # Optional whether this connection use TLS (default is true if server_port is 465)
+        secure: true
+        # Required mail subject:
+        subject: Github Actions job result
+        # Required recipients' addresses:
+        to: jhown_fs@hotmail.com
+        # Required sender full name (address can be skipped):
+        from: Devops team# <user@example.com>
+        # Optional plain body:
+        body: Build job of ${{github.repository}} completed successfully!
+        ignore_cert: true
+        # Optional attachments:
+        attachments: reports/scan-lwc.xml
+        # Optional priority: 'high', 'normal' (default) or 'low'
+        priority: low
